// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrT7c418zqDzoJLAjcoRElv99NClbDF4',
    appId: '1:1019804409974:web:2b90ce673a231c021e7f57',
    messagingSenderId: '1019804409974',
    projectId: 'promax-fe1c2',
    authDomain: 'promax-fe1c2.firebaseapp.com',
    databaseURL: 'https://promax-fe1c2-default-rtdb.firebaseio.com',
    storageBucket: 'promax-fe1c2.appspot.com',
    measurementId: 'G-2ZBZ2L26M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-RLUPiGjXQwnQEehQEVTcOiC4GVBA5Uk',
    appId: '1:1019804409974:android:b0695806f68068a71e7f57',
    messagingSenderId: '1019804409974',
    projectId: 'promax-fe1c2',
    databaseURL: 'https://promax-fe1c2-default-rtdb.firebaseio.com',
    storageBucket: 'promax-fe1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6A9o4RJIXtBzWEcXBXX3lMdpsvlP5wUs',
    appId: '1:1019804409974:ios:3b5925231512ef101e7f57',
    messagingSenderId: '1019804409974',
    projectId: 'promax-fe1c2',
    databaseURL: 'https://promax-fe1c2-default-rtdb.firebaseio.com',
    storageBucket: 'promax-fe1c2.appspot.com',
    androidClientId: '1019804409974-nom96u45sbkl1f64mhba8euso8h18928.apps.googleusercontent.com',
    iosClientId: '1019804409974-mvpa3l5b4lsolhiri2v8b4mlcvmf0771.apps.googleusercontent.com',
    iosBundleId: 'com.project.proMaxJect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6A9o4RJIXtBzWEcXBXX3lMdpsvlP5wUs',
    appId: '1:1019804409974:ios:3b5925231512ef101e7f57',
    messagingSenderId: '1019804409974',
    projectId: 'promax-fe1c2',
    databaseURL: 'https://promax-fe1c2-default-rtdb.firebaseio.com',
    storageBucket: 'promax-fe1c2.appspot.com',
    androidClientId: '1019804409974-nom96u45sbkl1f64mhba8euso8h18928.apps.googleusercontent.com',
    iosClientId: '1019804409974-mvpa3l5b4lsolhiri2v8b4mlcvmf0771.apps.googleusercontent.com',
    iosBundleId: 'com.project.proMaxJect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrT7c418zqDzoJLAjcoRElv99NClbDF4',
    appId: '1:1019804409974:web:05251d6e8ae261921e7f57',
    messagingSenderId: '1019804409974',
    projectId: 'promax-fe1c2',
    authDomain: 'promax-fe1c2.firebaseapp.com',
    databaseURL: 'https://promax-fe1c2-default-rtdb.firebaseio.com',
    storageBucket: 'promax-fe1c2.appspot.com',
    measurementId: 'G-BX179C37KY',
  );

}