import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class ReminderList extends StatelessWidget {
  const ReminderList({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.light().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        backgroundColor: Color(0xFFF0F1F0),
        body: ListView(
          children: [
            Reminder(),
          ],
        ),
      ),
    );
  }
}

class Reminder extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF0F1F0)),
          child: Stack(
            children: [
              Positioned(
                left: 19,
                top: 46,
                child: Container(
                  width: 291,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 70,
                        top: 2,
                        child: SizedBox(
                          width: 221,
                          child: Text(
                            '알림',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 22,
                              fontFamily: 'BM_HANNA_TTF',
                              height: 0.06,
                            ),
                          ),
                        ),
                      ),

                      /////////////   뒤로 가기 아이콘   ///////////
                      Positioned(
                        left: 0,
                        top: 1,
                        child: InkWell(
                          onTap: () {},
                          child: const Icon(
                            Icons.arrow_back,
                          )
                        ),
                      ),

                      ////////////   박스랑 관련있음   ////////////
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              /////////////////   알림 박스   //////////////////
              buildReminderBox(
                top: 120,
                text:
                    '폭염주의보 지속 발효 중. 부모님께 안부전화드리기, 야외활동 자제, 폭염 안전 수칙(물, 그늘, 휴식) 준수 등 건강관리에 유의 바랍니다. [인천광역시]',
              ),
              buildReminderBox(
                top: 212,
                text:
                    '폭염주의보 지속 발효 중. 부모님께 안부전화드리기, 야외활동 자제, 폭염 안전 수칙(물, 그늘, 휴식) 준수 등 건강관리에 유의 바랍니다. [인천광역시]',
              ),
              buildReminderBox(
                top: 304,
                text:
                    '폭염주의보 지속 발효 중. 부모님께 안부전화드리기, 야외활동 자제, 폭염 안전 수칙(물, 그늘, 휴식) 준수 등 건강관리에 유의 바랍니다. [인천광역시]',
              ),
              buildReminderBox(
                top: 396,
                text:
                    '폭염주의보 지속 발효 중. 부모님께 안부전화드리기, 야외활동 자제, 폭염 안전 수칙(물, 그늘, 휴식) 준수 등 건강관리에 유의 바랍니다. [인천광역시]',
              ),
              buildReminderBox(
                top: 488,
                text:
                    '폭염주의보 지속 발효 중. 부모님께 안부전화드리기, 야외활동 자제, 폭염 안전 수칙(물, 그늘, 휴식) 준수 등 건강관리에 유의 바랍니다. [인천광역시]',
              ),
              buildReminderBox(
                top: 580,
                text:
                    '폭염주의보 지속 발효 중. 부모님께 안부전화드리기, 야외활동 자제, 폭염 안전 수칙(물, 그늘, 휴식) 준수 등 건강관리에 유의 바랍니다. [인천광역시]',
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget buildReminderBox({required double top, String text = ''}) {
    return Positioned(
      left: 31,
      top: top,
      child: Container(
        width: 331,
        height: 77,
        decoration: ShapeDecoration(
          color: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(15),
          ),
          shadows: [
            BoxShadow(
              color: Color(0x30000000),
              blurRadius: 4,
              offset: Offset(0, 5),
              spreadRadius: 0,
            )
          ],
        ),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Container(
            padding: EdgeInsets.only(top: 8),
            child: Text(
              text,
              style: TextStyle(
                color: Color(0xFF24252C),
                fontSize: 11,
                fontFamily: 'Lexend Deca',
                fontWeight: FontWeight.w400,
                height: 1.6,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
